// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZ6wQwlLHtUELrVcKgz0AcuhziQ1rVTJw',
    appId: '1:447983947829:web:9e881f4650baa6fb35217c',
    messagingSenderId: '447983947829',
    projectId: 'agriconnect-5796a',
    authDomain: 'agriconnect-5796a.firebaseapp.com',
    storageBucket: 'agriconnect-5796a.firebasestorage.app',
    measurementId: 'G-VVNCDQV6DZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKLcyous9diQ_en8eG2yruYlILKHhpojA',
    appId: '1:447983947829:android:96477bc63a8f83ef35217c',
    messagingSenderId: '447983947829',
    projectId: 'agriconnect-5796a',
    storageBucket: 'agriconnect-5796a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQvAruSd5C9GC3tDAjxYLFiuipIYNEd50',
    appId: '1:447983947829:ios:6697f507e4e6762435217c',
    messagingSenderId: '447983947829',
    projectId: 'agriconnect-5796a',
    storageBucket: 'agriconnect-5796a.firebasestorage.app',
    iosBundleId: 'com.hyperlocal.hyperlocalMarket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQvAruSd5C9GC3tDAjxYLFiuipIYNEd50',
    appId: '1:447983947829:ios:6697f507e4e6762435217c',
    messagingSenderId: '447983947829',
    projectId: 'agriconnect-5796a',
    storageBucket: 'agriconnect-5796a.firebasestorage.app',
    iosBundleId: 'com.hyperlocal.hyperlocalMarket',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZ6wQwlLHtUELrVcKgz0AcuhziQ1rVTJw',
    appId: '1:447983947829:web:184de62f86278fe735217c',
    messagingSenderId: '447983947829',
    projectId: 'agriconnect-5796a',
    authDomain: 'agriconnect-5796a.firebaseapp.com',
    storageBucket: 'agriconnect-5796a.firebasestorage.app',
    measurementId: 'G-RB2M6RZXRX',
  );
}
