// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArepJ5S-653W7biy3dE5ppWOrzt4X8ivM',
    appId: '1:23199479661:web:eae4df76698df4fb3a8c64',
    messagingSenderId: '23199479661',
    projectId: 'hyperlocal-market-ba481',
    authDomain: 'hyperlocal-market-ba481.firebaseapp.com',
    storageBucket: 'hyperlocal-market-ba481.firebasestorage.app',
    measurementId: 'G-JQS3Y7F6BZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWTMth0KMF1G8_GimsQPWZpWOfW4W_uKc',
    appId: '1:23199479661:android:6ef56c48beb192be3a8c64',
    messagingSenderId: '23199479661',
    projectId: 'hyperlocal-market-ba481',
    storageBucket: 'hyperlocal-market-ba481.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQ3jU2WGoynrRN_xY2ww2DSKmMU-3pRY0',
    appId: '1:23199479661:ios:816a8689c0274ab73a8c64',
    messagingSenderId: '23199479661',
    projectId: 'hyperlocal-market-ba481',
    storageBucket: 'hyperlocal-market-ba481.firebasestorage.app',
    iosBundleId: 'com.hyperlocal.hyperlocalMarket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQ3jU2WGoynrRN_xY2ww2DSKmMU-3pRY0',
    appId: '1:23199479661:ios:816a8689c0274ab73a8c64',
    messagingSenderId: '23199479661',
    projectId: 'hyperlocal-market-ba481',
    storageBucket: 'hyperlocal-market-ba481.firebasestorage.app',
    iosBundleId: 'com.hyperlocal.hyperlocalMarket',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArepJ5S-653W7biy3dE5ppWOrzt4X8ivM',
    appId: '1:23199479661:web:5baa63b328ab87a13a8c64',
    messagingSenderId: '23199479661',
    projectId: 'hyperlocal-market-ba481',
    authDomain: 'hyperlocal-market-ba481.firebaseapp.com',
    storageBucket: 'hyperlocal-market-ba481.firebasestorage.app',
    measurementId: 'G-XH1SPXBSQM',
  );

}